server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: customersService
          uri: http://localhost:8081
          predicates:
            - Path=/customer/**
        - id: accountsService
          uri: http://localhost:8082
          predicates:
            - Path=/account/**
        - id: transactionsService
          uri: http://localhost:8083
          predicates:
            - Path=/transaction/**