openapi: 3.0.2

info:
  title: Account Service API
  version: 1.0.0

paths:
  /account/:
    post:
      summary: Create an account for a customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequestBody'
      responses:
        200:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponseBody'
        default:
          $ref: "#/components/schemas/AccountServiceError"

  /account/retrieveAccountBalanceByCustomerId/{customerId}:
    get:
      summary: Retrieve list of accounts for a customer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            allOf:
              - $ref: '#/components/schemas/CustomerID'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountBalance'
        default:
          $ref: "#/components/schemas/AccountServiceError"

components:
  schemas:
    CustomerResponseBody:
      type: object
      required:
        - customerId
        - name
        - surname
      properties:
        customerId:
          allOf:
            - $ref: '#/components/schemas/CustomerID'
        name:
          allOf:
            - $ref: '#/components/schemas/FirstName'
        surname:
          allOf:
            - $ref: '#/components/schemas/LastName'
    AccountServiceError:
      properties:
        message:
          type: string
          description: >
            Error message with details about the error.
    TransactionRequestBody:
      type: object
      required:
        - accountId
        - customerId
        - amount
      properties:
        accountId:
          $ref: '#/components/schemas/AccountID'
        amount:
          description: "Transaction Amount"
          type: string
        customerId:
          $ref: '#/components/schemas/CustomerID'

    AccountBalance:
      type: object
      required:
        - balance
      properties:
        balance:
          type: string

    AccountRequestBody:
      type: object
      required:
        - customerId
        - initialCredit
      properties:
        customerId:
          allOf:
            - $ref: '#/components/schemas/CustomerID'
        initialCredit:
          description: "Initial credit amount during the creation of the current account"
          type: string
    AccountResponseBody:
      type: object
      required:
        - accountId
        - balance
      properties:
        accountId:
          allOf:
            - $ref: '#/components/schemas/AccountID'
        balance:
          description: "Balance in the account"
          type: string

    Transaction:
      type: object
      required:
        - accountId
        - amount
        - customerId
        - date
      properties:
        accountId:
          allOf:
            - $ref: '#/components/schemas/AccountID'
        amount:
          description: "Transaction Amount"
          type: string
        customerId:
          allOf:
            - $ref: '#/components/schemas/CustomerID'
        date:
          description: "Date of the transaction"
          type: string

    CustomerID:
      type: integer
      format: int64
      description: "Unique ID of the customer"

    AccountID:
      type: integer
      format: int64
      description: "Unique ID of the account"

    FirstName:
      type: string
      description: "First name of the customer"

    LastName:
      type: string
      description: "Last name/Surname of the customer"
