server:
  port: 8082
spring:
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;
  jpa:
    defer-datasource-initialization: true

service:
  uri:
    customerServiceHostPort: http://localhost:8080
    transactionServiceHostPort: http://localhost:8080